name: CMake find_package() build

on: [ push ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hendrikmuhs/ccache-action@v1.2

      - name: Prepare package
        run: |
          mkdir my_packages
          mkdir pck && cd pck
          ls -la
          git clone https://github.com/tzaeschke/phtree-cpp.git
          cd phtree-cpp
          ls -la
          git checkout fix/83-cmake-find-package
          git status
          mkdir build && cd build
          ls -la
          echo "hello1"
          #args=("$GITHUB_WORKSPACE/pck/phtree-cpp" "-DPHTREE_INSTALL=on" "-DCMAKE_INSTALL_PREFIX:PATH='../../my_packages'")
          #echo "${args[@]}"
          cmake "${args[@]}"
          cmake $GITHUB_WORKSPACE/pck/phtree-cpp -DPHTREE_INSTALL=on -DCMAKE_INSTALL_PREFIX:PATH="../../../my_packages"
          ls -la
          echo "hello2"
          cmake --build . --config Release --target install -- -j2
          ls -la

#      - name: Prepare package 2
#        working-directory: ${{github.workspace}}/pck/build
#        run: cmake $GITHUB_WORKSPACE/pck -DPHTREE_INSTALL=on -DCMAKE_INSTALL_PREFIX:PATH="../../my_packages"
#
#      - name: Prepare package 3
#        working-directory: ${{github.workspace}}/pck/build
#        run: cmake --build . --config Release --target install -- -j2

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DPHT_CMAKE_FIND_PACKAGE=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE -j2

      #      - name: Test
      #        working-directory: ${{github.workspace}}/build
      #        run: ctest -C $BUILD_TYPE

      - name: Example
        working-directory: ${{github.workspace}}/build
        run: example-find-package/ExampleFind
